### ISSUE TITLE
Algorithm documentation

### ISSUE THREAD

**Issue by gari-marcos** [microsoft/TextWorld#174] opened 2019-07-27 12:31 UTC
Hi
The algorithm used in the **act** function of the Neural Agent in [Building a simple agent](https://github.com/microsoft/TextWorld/blob/master/notebooks/Building%20a%20simple%20agent.ipynb) is not explained. Would it be possible to document it? Thank you in advance.

**Comment by MarcCote** [comment] 2019-07-30 12:28
Duplicate of #158

**Closed by MarcCote** 2019-07-30 12:28 UTC
